version: '3.8'

services:
  computeruse-vm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: computeruse-vm
    ports:
      - "8080:8080"  # nginx (single entrypoint: frontend, API, noVNC, etc.)
      - "6080:6080"  # noVNC browser (if you want direct access for debug)
      - "5900:5900"  # VNC native client (if you want direct access for debug)
    environment:
      - DISPLAY_NUM=1
      - DISPLAY=:1
      - HEIGHT=768
      - WIDTH=1024
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=screenshots
      - EXTERNAL_URL=http://localhost:8080
    tmpfs:
      - /tmp:size=2g   # Option A: mount 2GB RAM-backed /tmp for fast access (change size as needed)
    depends_on:
      - minio
    # Uncomment below for Option B: map /tmp/outputs to a host folder for unlimited space
    # volumes:
    #   - ./outputs:/tmp/outputs

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
